# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop lib

test:
	OCAMLRUNPARAM=b dune exec test/main.exe

ltl2ba:
	OCAMLRUNPARAM=b dune exec bin/main.exe

# check:
# 	@bash check.sh

# finalcheck:
# 	@bash check.sh final

zip:
	rm -f final_project.zip
	zip -r final_project.zip . -x@exclude.lst

doc:
	dune build @doc

opendoc: doc
	@bash opendoc.sh

clean:
	dune clean
	rm -f final_project.zip
